# Generated by Django 2.1.5 on 2019-02-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='currency',
            field=models.CharField(default='руб.', max_length=4, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.CharField(blank=True, max_length=64, verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='products',
            name='href',
            field=models.CharField(max_length=64, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
    ]
