# Generated by Django 2.0.13 on 2019-03-05 11:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190303_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 7, 11, 20, 10, 910948, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
