# Generated by Django 2.1 on 2019-02-24 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20171225_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 12, 49, 39, 144940, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
